# -*- coding: utf-8 -*-
"""UAV Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BHN-JT0sRnMqyvPEoiD-i1jzlxWR3WqQ
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

print("TensorFlow:", tf.__version__)

from pathlib import Path

POS_DIR = Path("/content/drive/MyDrive/Concrete Crack Images for Classification/Positive")
NEG_DIR = Path("/content/drive/MyDrive/Concrete Crack Images for Classification/Negative")

assert POS_DIR.exists(), f"Not found: {POS_DIR}"
assert NEG_DIR.exists(), f"Not found: {NEG_DIR}"

MAX_PER_CLASS = 10000

pos_files = sorted(list(POS_DIR.glob("*.jpg")))[:MAX_PER_CLASS]
neg_files = sorted(list(NEG_DIR.glob("*.jpg")))[:MAX_PER_CLASS]

print("Positive:", len(pos_files))
print("Negative:", len(neg_files))

print("sample positive:", pos_files[:3])
print("sample negative:", neg_files[:3])

"""データフレームの作成

PotitiveとNegativeを混ぜ、シャッフルして番号を振る
"""

df_pos = pd.DataFrame({
    "filepath": [str(p) for p in pos_files],
    "label": 1
})

df_neg = pd.DataFrame({
    "filepath": [str(p) for p in neg_files],
    "label": 0
})

df = pd.concat([df_pos, df_neg], ignore_index=True)
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

print(df.head())
print(df["label"].value_counts())

"""データを3つに分ける

train（学習用）
val（検証用）
test（最終評価用）

      ┌─────┐
      │ train    │ → モデルを作る
      └─────┘
           ↓
      ┌─────┐
      │ val      │ → 改善・調整
      └─────┘
           ↓
      ┌─────┐
      │ test     │ → 最終チェック
      └─────┘
"""

train_df, temp_df = train_test_split(
    df,
    test_size=0.30,
    stratify=df["label"],
    random_state=42
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    stratify=temp_df["label"],
    random_state=42
)

print("train:", len(train_df))
print("val  :", len(val_df))
print("test :", len(test_df))

print(train_df["label"].value_counts())
print(val_df["label"].value_counts())
print(test_df["label"].value_counts())

IMG_SIZE = (160, 160)
BATCH_SIZE = 32
AUTOTUNE = tf.data.AUTOTUNE

"""画像をモデルが理解できる数値に変換<br>
DataFrame → Dataset に変換<br>
（注）train時のみ、画像の明るさや向きをシャッフルする処理を挟む
"""

def decode_img(path, label):
    img = tf.io.read_file(path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, IMG_SIZE)
    img = tf.cast(img, tf.float32) / 255.0
    return img, tf.cast(label, tf.float32)

def make_dataset(dataframe, training=False):
    paths = dataframe["filepath"].values
    labels = dataframe["label"].values

    ds = tf.data.Dataset.from_tensor_slices((paths, labels))
    ds = ds.map(decode_img, num_parallel_calls=AUTOTUNE)

    if training:
        ds = ds.shuffle(2000, seed=42)

        ds = ds.map(
            lambda x, y: (
                tf.image.random_flip_left_right(x),
                y
            ),
            num_parallel_calls=AUTOTUNE
        )

        ds = ds.map(
            lambda x, y: (
                tf.image.random_brightness(x, max_delta=0.1),
                y
            ),
            num_parallel_calls=AUTOTUNE
        )

    ds = ds.batch(BATCH_SIZE).prefetch(AUTOTUNE)
    return ds

train_ds = make_dataset(train_df, training=True)
val_ds   = make_dataset(val_df, training=False)
test_ds  = make_dataset(test_df, training=False)

images, labels = next(iter(train_ds))

plt.figure(figsize=(12, 6))
for i in range(8):
    plt.subplot(2, 4, i+1)
    plt.imshow(images[i].numpy())
    plt.title("Positive" if labels[i].numpy() == 1 else "Negative")
    plt.axis("off")
plt.tight_layout()
plt.show()

"""MobileNet ： スマホなどの小型端末にも乗せられる高性能CNNを作りたいというモチベーションから生まれた軽量かつ高性能なCNN<br>
入力画像<br>
   ↓<br>
MobileNetV2（特徴抽出器）※凍結<br>
   ↓<br>
Pooling + Dropout<br>
   ↓<br>
全結合（分類）<br>
   ↓<br>
出力（0〜1）<br><br>
以下サマリ構成<br>
入力層：入力画像<br>
前処理部分：① ×255 → 0〜1 → 0〜255 に戻す<br>
　　　　　　② ÷127.5<br>
　　　　　　③ -1<br>
GlobalAveragePooling：空間情報を作成<br>
Dropout：過学習防止のため20％ランダムで落とす<br>
特徴抽出は既存モデルに任せて、最後だけ自分用に調整

"""

base_model = tf.keras.applications.MobileNetV2(
    input_shape=(IMG_SIZE[0], IMG_SIZE[1], 3),
    include_top=False,
    weights="imagenet"
)

base_model.trainable = False

inputs = tf.keras.Input(shape=(IMG_SIZE[0], IMG_SIZE[1], 3))
x = tf.keras.applications.mobilenet_v2.preprocess_input(inputs * 255.0)
x = base_model(x, training=False)
x = tf.keras.layers.GlobalAveragePooling2D()(x)
x = tf.keras.layers.Dropout(0.2)(x)
outputs = tf.keras.layers.Dense(1, activation="sigmoid")(x)

model = tf.keras.Model(inputs, outputs)

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-3),
    loss="binary_crossentropy",
    metrics=[
        "accuracy",
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall"),
        tf.keras.metrics.AUC(name="auc")
    ]
)

model.summary()

checkpoint_path = "/content/drive/MyDrive/crack_classifier_best.keras"

callbacks = [
    tf.keras.callbacks.ModelCheckpoint(
        checkpoint_path,
        monitor="val_auc",
        mode="max",
        save_best_only=True,
        verbose=1
    ),
    tf.keras.callbacks.EarlyStopping(
        monitor="val_auc",
        mode="max",
        patience=3,
        restore_best_weights=True,
        verbose=1
    ),
    tf.keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=2,
        verbose=1
    )
]

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=5,
    callbacks=callbacks
)

hist = pd.DataFrame(history.history)

plt.figure(figsize=(12, 4))

plt.subplot(1, 3, 1)
plt.plot(hist["loss"], label="train")
plt.plot(hist["val_loss"], label="val")
plt.title("Loss")
plt.legend()

plt.subplot(1, 3, 2)
plt.plot(hist["accuracy"], label="train")
plt.plot(hist["val_accuracy"], label="val")
plt.title("Accuracy")
plt.legend()

plt.subplot(1, 3, 3)
plt.plot(hist["auc"], label="train")
plt.plot(hist["val_auc"], label="val")
plt.title("AUC")
plt.legend()

plt.tight_layout()
plt.show()

base_model.trainable = True

for layer in base_model.layers[:-30]:
    layer.trainable = False

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-5),
    loss="binary_crossentropy",
    metrics=[
        "accuracy",
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall"),
        tf.keras.metrics.AUC(name="auc")
    ]
)

history_ft = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=5,
    callbacks=callbacks
)

best_model = tf.keras.models.load_model(checkpoint_path)

test_metrics = best_model.evaluate(test_ds, verbose=1)
print(dict(zip(best_model.metrics_names, test_metrics)))

y_true = test_df["label"].values

y_prob = best_model.predict(test_ds, verbose=1).ravel()
y_pred = (y_prob >= 0.5).astype(int)

print(classification_report(y_true, y_pred, target_names=["Negative", "Positive"]))

cm = confusion_matrix(y_true, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Negative", "Positive"])
disp.plot(cmap="Blues")
plt.show()

"""テストデータの画像をランダムに表示して、予測結果を可視化する"""

sample_df = test_df.sample(8, random_state=42).reset_index(drop=True)

plt.figure(figsize=(12, 6))
for i in range(8):
    path = sample_df.loc[i, "filepath"]
    true_label = sample_df.loc[i, "label"]

    img = tf.keras.utils.load_img(path, target_size=IMG_SIZE)
    x = tf.keras.utils.img_to_array(img) / 255.0
    pred = best_model.predict(np.expand_dims(x, axis=0), verbose=0)[0][0]

    plt.subplot(2, 4, i+1)
    plt.imshow(img)
    plt.title(
        f"T:{'Pos' if true_label==1 else 'Neg'}\nP:{pred:.3f}"
    )
    plt.axis("off")

plt.tight_layout()
plt.show()

def get_last_conv_layer_name(model):
    for layer in reversed(model.layers):
        if len(layer.output.shape) == 4:
            return layer.name
    raise ValueError("4次元出力の層が見つからない")

last_conv_layer_name = get_last_conv_layer_name(best_model)
print("last conv layer:", last_conv_layer_name)

four_d_layers = []

for layer in best_model.layers:
    try:
        shape = layer.output.shape
        if len(shape) == 4:
            four_d_layers.append((layer.name, shape))
    except:
        pass

print(four_d_layers)

LAST_CONV_LAYER_NAME = "mobilenetv2_1.00_160"

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

# 1) ネストされた base_model を取得
base_idx = None
base_model_layer = None

for i, layer in enumerate(best_model.layers):
    if isinstance(layer, tf.keras.Model):
        base_idx = i
        base_model_layer = layer
        break

print("base_idx:", base_idx)
print("base_model_layer:", base_model_layer.name)

# 2) MobileNetV2 の最後の畳み込み出力を取るモデル
# include_top=False の MobileNetV2 では out_relu が最終 conv 出力
LAST_CONV_IN_BASE = "out_relu"

last_conv_layer_model = tf.keras.Model(
    inputs=base_model_layer.input,
    outputs=base_model_layer.get_layer(LAST_CONV_IN_BASE).output
)

print("last conv output shape:", last_conv_layer_model.output_shape)

# 3) 分類ヘッドだけを後ろに再構成
classifier_input = tf.keras.Input(shape=last_conv_layer_model.output_shape[1:])
x = classifier_input

for layer in best_model.layers[base_idx + 1:]:
    try:
        x = layer(x, training=False)
    except TypeError:
        x = layer(x)

classifier_model = tf.keras.Model(classifier_input, x)
print("classifier output shape:", classifier_model.output_shape)


def load_image_raw(img_path, target_size=IMG_SIZE):
    img = tf.keras.utils.load_img(img_path, target_size=target_size)
    arr = tf.keras.utils.img_to_array(img).astype("float32")  # 0..255
    arr = np.expand_dims(arr, axis=0)
    return img, arr


def make_gradcam_heatmap_safe(img_path):
    img_pil, img_raw = load_image_raw(img_path, target_size=IMG_SIZE)

    # MobileNetV2 用の正しい前処理
    img_pp = tf.keras.applications.mobilenet_v2.preprocess_input(img_raw.copy())

    with tf.GradientTape() as tape:
        last_conv_output = last_conv_layer_model(img_pp, training=False)
        tape.watch(last_conv_output)

        preds = classifier_model(last_conv_output, training=False)
        class_score = preds[:, 0]  # sigmoid binary output

    grads = tape.gradient(class_score, last_conv_output)

    # mixed precision対策も兼ねて float32 にそろえる
    last_conv_output = tf.cast(last_conv_output, tf.float32)
    grads = tf.cast(grads, tf.float32)

    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))
    conv_output = last_conv_output[0]  # (H, W, C)

    heatmap = tf.reduce_sum(conv_output * pooled_grads, axis=-1)
    heatmap = tf.maximum(heatmap, 0)
    heatmap = heatmap / (tf.reduce_max(heatmap) + 1e-8)

    return img_pil, img_raw[0].astype("uint8"), heatmap.numpy(), float(preds[0, 0])


def display_gradcam_safe(img_path, alpha=0.4):
    img_pil, img_uint8, heatmap, pred = make_gradcam_heatmap_safe(img_path)

    heatmap_uint8 = np.uint8(255 * heatmap)

    cmap = plt.get_cmap("jet")
    jet_colors = cmap(np.arange(256))[:, :3]
    jet_heatmap = jet_colors[heatmap_uint8]
    jet_heatmap = tf.keras.utils.array_to_img(jet_heatmap)
    jet_heatmap = jet_heatmap.resize((img_uint8.shape[1], img_uint8.shape[0]))
    jet_heatmap = tf.keras.utils.img_to_array(jet_heatmap)

    overlay = jet_heatmap * alpha + img_uint8
    overlay = np.clip(overlay / 255.0, 0, 1)

    plt.figure(figsize=(12, 4))

    plt.subplot(1, 3, 1)
    plt.imshow(img_uint8)
    plt.title(f"Input\nPred={pred:.3f}")
    plt.axis("off")

    plt.subplot(1, 3, 2)
    plt.imshow(heatmap, cmap="jet")
    plt.title("Grad-CAM Heatmap")
    plt.axis("off")

    plt.subplot(1, 3, 3)
    plt.imshow(overlay)
    plt.title("Overlay")
    plt.axis("off")

    plt.tight_layout()
    plt.show()

    return heatmap, pred

sample_path = test_df.sample(1, random_state=9)["filepath"].iloc[0]
print(sample_path)

heatmap, pred = display_gradcam_safe(sample_path)

"""画像<br>
→ Grad-CAMで注目領域を出す<br>
→ しきい値で白黒マスク化<br>
→ ノイズ除去<br>
→ 輪郭抽出<br>
→ 元画像に重ねて可視化
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

def heatmap_to_mask_safe(heatmap, threshold=0.5):
    mask = (heatmap >= threshold).astype(np.uint8) * 255

    kernel = np.ones((3, 3), np.uint8)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)

    return mask

def display_mask_overlay_safe(img_path, threshold=0.5):
    # ここは safe版 Grad-CAM を使う
    img_pil, img_uint8, heatmap, pred = make_gradcam_heatmap_safe(img_path)

    # heatmap を入力画像サイズに合わせる
    heatmap_resized = cv2.resize(
        heatmap,
        (img_uint8.shape[1], img_uint8.shape[0])
    )

    mask = heatmap_to_mask_safe(heatmap_resized, threshold=threshold)

    overlay = img_uint8.copy()
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    cv2.drawContours(overlay, contours, -1, (255, 0, 0), 2)

    plt.figure(figsize=(16, 4))

    plt.subplot(1, 4, 1)
    plt.imshow(img_uint8)
    plt.title(f"Input\nPred={pred:.3f}")
    plt.axis("off")

    plt.subplot(1, 4, 2)
    plt.imshow(heatmap_resized, cmap="jet")
    plt.title("Heatmap")
    plt.axis("off")

    plt.subplot(1, 4, 3)
    plt.imshow(mask, cmap="gray")
    plt.title("Estimated Mask")
    plt.axis("off")

    plt.subplot(1, 4, 4)
    plt.imshow(overlay)
    plt.title("Contour Overlay")
    plt.axis("off")

    plt.tight_layout()
    plt.show()

    return heatmap_resized, mask, overlay, pred

heatmap_resized, mask, overlay, pred = display_mask_overlay_safe(
    sample_path,
    threshold=0.5
)

from pathlib import Path

SAVE_DIR = Path("/content/drive/MyDrive/crack_gradcam_outputs")
SAVE_DIR.mkdir(exist_ok=True)

def save_visualization_set_safe(img_path, threshold=0.5):
    img_pil, img_uint8, heatmap, pred = make_gradcam_heatmap_safe(img_path)

    heatmap_resized = cv2.resize(
        heatmap,
        (img_uint8.shape[1], img_uint8.shape[0])
    )
    mask = heatmap_to_mask_safe(heatmap_resized, threshold=threshold)

    overlay = img_uint8.copy()
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    cv2.drawContours(overlay, contours, -1, (255, 0, 0), 2)

    stem = Path(img_path).stem

    plt.imsave(SAVE_DIR / f"{stem}_input.png", img_uint8.astype(np.uint8))
    plt.imsave(SAVE_DIR / f"{stem}_heatmap.png", heatmap_resized, cmap="jet")
    plt.imsave(SAVE_DIR / f"{stem}_mask.png", mask, cmap="gray")
    plt.imsave(SAVE_DIR / f"{stem}_overlay.png", overlay.astype(np.uint8))

    print(f"saved: {stem}, pred={pred:.3f}")

save_visualization_set_safe(sample_path, threshold=0.5)

converter = tf.lite.TFLiteConverter.from_keras_model(best_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()

tflite_path = "/content/drive/MyDrive/crack_classifier_mobilenetv2.tflite"
with open(tflite_path, "wb") as f:
    f.write(tflite_model)

print("saved:", tflite_path)

import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

# 予測確率
y_prob = best_model.predict(test_ds, verbose=1).ravel()
y_true = test_df["label"].values
y_pred = (y_prob >= 0.5).astype(int)

results_df = test_df.copy().reset_index(drop=True)
results_df["y_true"] = y_true
results_df["y_prob"] = y_prob
results_df["y_pred"] = y_pred

def judge(row):
    if row["y_true"] == 1 and row["y_pred"] == 1:
        return "TP"
    elif row["y_true"] == 0 and row["y_pred"] == 0:
        return "TN"
    elif row["y_true"] == 0 and row["y_pred"] == 1:
        return "FP"
    else:
        return "FN"

results_df["case"] = results_df.apply(judge, axis=1)

acc = accuracy_score(y_true, y_pred)
pre = precision_score(y_true, y_pred)
rec = recall_score(y_true, y_pred)
f1  = f1_score(y_true, y_pred)
auc = roc_auc_score(y_true, y_prob)

print(f"Accuracy : {acc:.4f}")
print(f"Precision: {pre:.4f}")
print(f"Recall   : {rec:.4f}")
print(f"F1-score : {f1:.4f}")
print(f"AUC      : {auc:.4f}")

print(results_df["case"].value_counts())
results_df.head()

import matplotlib.pyplot as plt
import tensorflow as tf

def show_cases(results_df, case_name, n=6):
    sub = results_df[results_df["case"] == case_name].sample(min(n, len(results_df[results_df["case"] == case_name])), random_state=42)
    plt.figure(figsize=(12, 6))
    for i, (_, row) in enumerate(sub.iterrows()):
        img = tf.keras.utils.load_img(row["filepath"], target_size=IMG_SIZE)
        plt.subplot(2, 3, i+1)
        plt.imshow(img)
        plt.title(f"{case_name}\ntrue={row['y_true']} pred={row['y_pred']}\np={row['y_prob']:.3f}")
        plt.axis("off")
    plt.tight_layout()
    plt.show()

show_cases(results_df, "TP")
show_cases(results_df, "FP")
show_cases(results_df, "FN")
show_cases(results_df, "TN")

# 信頼度の高いTPを2枚
tp_best = results_df[results_df["case"] == "TP"].sort_values("y_prob", ascending=False).head(2)

# 誤検出FPを2枚
fp_examples = results_df[results_df["case"] == "FP"].sort_values("y_prob", ascending=False).head(2)

# 見逃しFNを2枚
fn_examples = results_df[results_df["case"] == "FN"].sort_values("y_prob", ascending=True).head(2)

# 正常TNを2枚
tn_best = results_df[results_df["case"] == "TN"].sort_values("y_prob", ascending=True).head(2)

for df_sub in [tp_best, fp_examples, fn_examples, tn_best]:
    for _, row in df_sub.iterrows():
        save_visualization_set_safe(row["filepath"], threshold=0.5)

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc

y_true = results_df["y_true"].values
y_prob = results_df["y_prob"].values

fpr, tpr, thresholds = roc_curve(y_true, y_prob)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(5, 5))
plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.4f}")
plt.plot([0, 1], [0, 1], linestyle="--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

print("history epochs:", len(history.history["loss"]))
for k, v in history.history.items():
    print(k, "->", v)

from sklearn.metrics import precision_recall_curve, average_precision_score

precision, recall, pr_thresholds = precision_recall_curve(y_true, y_prob)
ap = average_precision_score(y_true, y_prob)

plt.figure(figsize=(5, 5))
plt.plot(recall, precision, label=f"AP = {ap:.4f}")
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve")
plt.legend(loc="lower left")
plt.grid(True)
plt.show()

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm = confusion_matrix(y_true, results_df["y_pred"].values)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Negative", "Positive"])
disp.plot(cmap="Blues")
plt.title("Confusion Matrix")
plt.show()

import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

thresholds_to_check = [0.3, 0.4, 0.5, 0.6, 0.7]
rows = []

for th in thresholds_to_check:
    y_pred_th = (y_prob >= th).astype(int)
    rows.append({
        "threshold": th,
        "accuracy": accuracy_score(y_true, y_pred_th),
        "precision": precision_score(y_true, y_pred_th, zero_division=0),
        "recall": recall_score(y_true, y_pred_th, zero_division=0),
        "f1": f1_score(y_true, y_pred_th, zero_division=0),
        "TP": int(((y_true == 1) & (y_pred_th == 1)).sum()),
        "TN": int(((y_true == 0) & (y_pred_th == 0)).sum()),
        "FP": int(((y_true == 0) & (y_pred_th == 1)).sum()),
        "FN": int(((y_true == 1) & (y_pred_th == 0)).sum()),
    })

threshold_df = pd.DataFrame(rows)
threshold_df

plt.figure(figsize=(7, 5))
plt.plot(threshold_df["threshold"], threshold_df["precision"], marker="o", label="Precision")
plt.plot(threshold_df["threshold"], threshold_df["recall"], marker="o", label="Recall")
plt.plot(threshold_df["threshold"], threshold_df["f1"], marker="o", label="F1")
plt.xlabel("Threshold")
plt.ylabel("Score")
plt.title("Threshold vs Metrics")
plt.legend()
plt.grid(True)
plt.show()

from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.metrics import brier_score_loss
import numpy as np

rmse = np.sqrt(mean_squared_error(y_true, y_prob))
mae = mean_absolute_error(y_true, y_prob)
brier = brier_score_loss(y_true, y_prob)

print(f"RMSE       : {rmse:.4f}")
print(f"MAE        : {mae:.4f}")
print(f"Brier score: {brier:.4f}")

plt.figure(figsize=(5, 5))
plt.scatter(y_true, y_prob, alpha=0.2)
plt.plot([0, 1], [0, 1], linestyle="--")
plt.xlabel("True Label")
plt.ylabel("Predicted Probability")
plt.title("yyplot (True vs Predicted Probability)")
plt.grid(True)
plt.show()

x_jitter = y_true + np.random.normal(0, 0.03, size=len(y_true))

plt.figure(figsize=(5, 5))
plt.scatter(x_jitter, y_prob, alpha=0.2)
plt.plot([0, 1], [0, 1], linestyle="--")
plt.xlim(-0.2, 1.2)
plt.ylim(-0.05, 1.05)
plt.xlabel("True Label (jittered)")
plt.ylabel("Predicted Probability")
plt.title("yyplot (Jittered)")
plt.grid(True)
plt.show()

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

summary_table = pd.DataFrame([{
    "Accuracy": accuracy_score(y_true, results_df["y_pred"]),
    "Precision": precision_score(y_true, results_df["y_pred"], zero_division=0),
    "Recall": recall_score(y_true, results_df["y_pred"], zero_division=0),
    "F1-score": f1_score(y_true, results_df["y_pred"], zero_division=0),
    "ROC-AUC": roc_auc_score(y_true, y_prob),
    "AP": average_precision_score(y_true, y_prob),
    "RMSE": rmse,
    "MAE": mae,
    "Brier": brier
}])

summary_table

import pandas as pd
import matplotlib.pyplot as plt

hist1 = pd.DataFrame(history.history)
hist2 = pd.DataFrame(history_ft.history)

hist_all = pd.concat([hist1, hist2], ignore_index=True)
hist_all["epoch"] = range(1, len(hist_all) + 1)

plt.figure(figsize=(12,4))

plt.subplot(1,3,1)
plt.plot(hist_all["epoch"], hist_all["loss"], marker="o", label="train")
plt.plot(hist_all["epoch"], hist_all["val_loss"], marker="o", label="val")
plt.title("Loss")
plt.xlabel("Epoch")
plt.legend()

plt.subplot(1,3,2)
plt.plot(hist_all["epoch"], hist_all["accuracy"], marker="o", label="train")
plt.plot(hist_all["epoch"], hist_all["val_accuracy"], marker="o", label="val")
plt.title("Accuracy")
plt.xlabel("Epoch")
plt.legend()

plt.subplot(1,3,3)
plt.plot(hist_all["epoch"], hist_all["auc"], marker="o", label="train")
plt.plot(hist_all["epoch"], hist_all["val_auc"], marker="o", label="val")
plt.title("AUC")
plt.xlabel("Epoch")
plt.legend()

plt.tight_layout()
plt.show()