import { CreateEventInput, EventSeverity } from "../models/event";
import { EventStatus } from "../models/event";
import { DetectImageInput } from "../types/detection";
import { ListEventsQuery, UpdateStatusInput, UploadContentType, UploadUrlInput } from "../types/event";
import { RequestValidationError } from "./errors";

export const allowedEventStatuses: EventStatus[] = ["NEW", "CHECKING", "RESOLVED"];
export const allowedEventSeverities: EventSeverity[] = ["LOW", "MEDIUM", "HIGH"];
export const allowedUploadContentTypes: UploadContentType[] = ["image/jpeg", "image/png", "image/webp"];

function isNonEmptyString(value: unknown): value is string {
  return typeof value === "string" && value.trim().length > 0;
}

function isFiniteNumber(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value);
}

function isValidIsoDateTime(value: unknown): value is string {
  return typeof value === "string" && !Number.isNaN(Date.parse(value));
}

// Reject keys that could escape the storage root (path traversal) or use OS
// path separators / absolute paths. Object keys generated by the API look like
// "images/<uuid>.<ext>", so forward-slash separated relative segments are fine.
function isSafeStorageKey(value: string): boolean {
  if (value.includes("\\") || value.includes("\0")) {
    return false;
  }
  if (value.startsWith("/") || /^[a-zA-Z]:/.test(value)) {
    return false;
  }
  return !value.split("/").includes("..");
}

export function parseJson<T>(body: string | null | undefined): T | null {
  if (!body) return null;
  try {
    return JSON.parse(body) as T;
  } catch {
    throw new RequestValidationError("Request body must be valid JSON");
  }
}

export function validateCreateEventInput(input: Partial<CreateEventInput> | null): string[] {
  const errors: string[] = [];

  if (!input) {
    return ["Request body is required"];
  }

  if (!isNonEmptyString(input.deviceId)) {
    errors.push("deviceId must be a non-empty string");
  }

  if (!isNonEmptyString(input.sectionId)) {
    errors.push("sectionId must be a non-empty string");
  }

  if (!isFiniteNumber(input.distance) || input.distance < 0) {
    errors.push("distance must be a number greater than or equal to 0");
  }

  if (!isValidIsoDateTime(input.detectedAt)) {
    errors.push("detectedAt must be a valid ISO 8601 date-time string");
  }

  if (!isFiniteNumber(input.confidence) || input.confidence < 0 || input.confidence > 1) {
    errors.push("confidence must be a number between 0 and 1");
  }

  if (input.severity !== undefined && !allowedEventSeverities.includes(input.severity)) {
    errors.push("severity must be one of LOW, MEDIUM, HIGH");
  }

  if (input.detectionProvider !== undefined && !isNonEmptyString(input.detectionProvider)) {
    errors.push("detectionProvider must be a non-empty string when provided");
  }

  if (input.topLabel !== undefined && !isNonEmptyString(input.topLabel)) {
    errors.push("topLabel must be a non-empty string when provided");
  }

  if (input.evidenceSummary !== undefined && !isNonEmptyString(input.evidenceSummary)) {
    errors.push("evidenceSummary must be a non-empty string when provided");
  }

  if (input.insightTags !== undefined) {
    if (!Array.isArray(input.insightTags) || input.insightTags.some((tag) => !isNonEmptyString(tag))) {
      errors.push("insightTags must be an array of non-empty strings when provided");
    }
  }

  if (input.imageKey !== undefined && !isNonEmptyString(input.imageKey)) {
    errors.push("imageKey must be a non-empty string when provided");
  }

  if (input.note !== undefined && typeof input.note !== "string") {
    errors.push("note must be a string when provided");
  }

  return errors;
}

export function validateListEventsQuery(query: Partial<Record<keyof ListEventsQuery, unknown>>): string[] {
  const errors: string[] = [];

  if (query.status !== undefined && !allowedEventStatuses.includes(query.status as EventStatus)) {
    errors.push("status must be one of NEW, CHECKING, RESOLVED");
  }

  if (query.deviceId !== undefined && !isNonEmptyString(query.deviceId)) {
    errors.push("deviceId must be a non-empty string when provided");
  }

  return errors;
}

export function validateUpdateStatusInput(input: Partial<UpdateStatusInput> | null): string[] {
  const errors: string[] = [];

  if (!input) {
    return ["Request body is required"];
  }

  if (!allowedEventStatuses.includes(input.status as EventStatus)) {
    errors.push("status must be one of NEW, CHECKING, RESOLVED");
  }

  return errors;
}

export function isValidUpdateStatusInput(input: Partial<UpdateStatusInput> | null): input is UpdateStatusInput {
  return validateUpdateStatusInput(input).length === 0;
}

export function validateUploadUrlInput(input: Partial<UploadUrlInput> | null): string[] {
  const errors: string[] = [];

  if (!input) {
    return ["Request body is required"];
  }

  if (!allowedUploadContentTypes.includes(input.contentType as UploadContentType)) {
    errors.push("contentType must be one of image/jpeg, image/png, image/webp");
  }

  return errors;
}

export function validateDetectImageInput(input: Partial<DetectImageInput> | null): string[] {
  const errors: string[] = [];

  if (!input) {
    return ["Request body is required"];
  }

  if (!isNonEmptyString(input.deviceId)) {
    errors.push("deviceId must be a non-empty string");
  }

  if (!isNonEmptyString(input.sectionId)) {
    errors.push("sectionId must be a non-empty string");
  }

  if (!isFiniteNumber(input.distance) || input.distance < 0) {
    errors.push("distance must be a number greater than or equal to 0");
  }

  if (!isValidIsoDateTime(input.detectedAt)) {
    errors.push("detectedAt must be a valid ISO 8601 date-time string");
  }

  if (!isNonEmptyString(input.imageKey)) {
    errors.push("imageKey must be a non-empty string");
  } else if (!isSafeStorageKey(input.imageKey)) {
    errors.push("imageKey must not contain path traversal segments or absolute paths");
  }

  if (input.imageContentType !== undefined && typeof input.imageContentType !== "string") {
    errors.push("imageContentType must be a string when provided");
  }

  if (input.imageDataBase64 !== undefined && !isNonEmptyString(input.imageDataBase64)) {
    errors.push("imageDataBase64 must be a non-empty base64 string when provided");
  }

  if (input.note !== undefined && typeof input.note !== "string") {
    errors.push("note must be a string when provided");
  }

  return errors;
}
